version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: logto
      POSTGRES_PASSWORD: logto
      POSTGRES_DB: logto
    volumes:
      - logto_db:/var/lib/postgresql/data
    labels:
      - coolify.hidden=true   # hide from Coolify UI, it's just a dependency
  logto:
    image: ghcr.io/logto-io/logto:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      TRUST_PROXY_HEADER: 1
      LOG_LEVEL: info
      DB_URL: postgres://logto:logto@postgres:5432/logto
      ENDPOINT: https://logto.open-elements.cloud
      ADMIN_ENDPOINT: https://logto.open-elements.cloud/console
    ports:
      - "3001:3001"
      - "3002:3002"
    volumes:
      - logto_data:/root/.logto
    entrypoint: ["/bin/sh", "-c"]
    command: ["npm run cli db seed -- --swe && npm run alteration deploy && npm start"]
    labels:
      - coolify.main=true     # mark this as the main service in Coolify
volumes:
  logto_db:
  logto_data: