version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: logto
      POSTGRES_PASSWORD: logto
      POSTGRES_DB: logto
    volumes:
      - logto_db:/var/lib/postgresql/data

  logto:
    image: ghcr.io/logto-io/logto:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      TRUST_PROXY_HEADER: 1
      LOG_LEVEL: info
      DB_URL: postgres://logto:logto@postgres:5432/logto
      ENDPOINT: https://auth.yourdomain.com
    ports:
      - "3001:3001"
    volumes:
      - logto_data:/root/.logto
    command: >
      sh -c "
        npm run alteration deploy &&
        npm run start
      "

volumes:
  logto_db:
  logto_data:
