version: "3.8"
services:
  logto:
    image: node:22
    container_name: logto
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./init-tenants.sh:/usr/src/app/init-tenants.sh
    ports:
      - "3001:3001" # core
      - "3002:3002" # admin
    environment:
      NODE_ENV: production
      DB_URL: postgres://logto:logto@postgres:5432/logto
      ADMIN_ENDPOINT: https://logto.open-elements.cloud/console
      ENDPOINT: https://logto.open-elements.cloud
      TRUST_PROXY_HEADER: "1"
    depends_on:
      - postgres
    command: ["sh", "./init-tenants.sh"]

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: logto
      POSTGRES_PASSWORD: logto
      POSTGRES_DB: logto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
