version: '3.9'

services:
  logto:
    image: ghcr.io/logto-io/logto:latest
    container_name: logto
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      TRUST_PROXY_HEADER: 1
      LOG_LEVEL: info
      DB_URL: postgres://logto:logto@postgres:5432/logto
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: logto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: logto
      POSTGRES_PASSWORD: logto
      POSTGRES_DB: logto
    volumes:
      - logto_db:/var/lib/postgresql/data

volumes:
  logto_db:
